package component:smartcms;

interface kvstore {
    get: func(key: string) -> string;
    set: func(key: string, value: string);
}

world app {
    import kvstore;

    export run: func() -> string;
}